import type { Config } from "tailwindcss";
import defaultTheme from "tailwindcss/defaultTheme";

const config: Config = {
  darkMode: "class",
  content: {
    relative: true,
    files: [
      "./app/**/*.{js,ts,jsx,tsx,mdx}",
      "./components/**/*.{js,ts,jsx,tsx,mdx}",
      "./lib/**/*.{js,ts,jsx,tsx,mdx}",
      "../../packages/*/src/**/*.{js,ts,jsx,tsx,mdx}",
    ],
  },
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        'bg-alt': 'var(--bg-alt)',
        surface: 'var(--surface)',
        'surface-strong': 'var(--surface-strong)',
        line: 'var(--line)',
        text: 'var(--text)',
        muted: 'var(--muted)',
        accent: 'var(--accent)',
        'accent-soft': 'var(--accent-soft)',
        warning: 'var(--warning)',
        'warning-soft': 'var(--warning-soft)',
        success: 'var(--success)',
        'success-soft': 'var(--success-soft)',
        'surface-sunken': 'var(--surface-sunken)',
        'line-subtle': 'var(--line-subtle)',
        'text-strong': 'var(--text-strong)',
        info: 'var(--info)',
        'info-soft': 'var(--info-soft)',
        danger: 'var(--danger)',
        'danger-soft': 'var(--danger-soft)',
        'danger-border': 'var(--danger-border)',
        'warning-bg': 'var(--warning-bg)',
        'accent-fg': 'var(--accent-fg)',
        'success-border': 'var(--success-border)',
        'danger-hover': 'var(--danger-hover)',
        pending: 'var(--pending)',
        'pending-soft': 'var(--pending-soft)',
        'pending-border': 'var(--pending-border)',
        'code-bg': 'var(--code-bg)',
        'code-fg': 'var(--code-fg)',
        brand: {
          50: 'var(--brand-50)',
          100: 'var(--brand-100)',
          200: 'var(--brand-200)',
          300: 'var(--brand-300)',
          400: 'var(--brand-400)',
          500: 'var(--brand-500)',
          600: 'var(--brand-600)',
          700: 'var(--brand-700)',
          800: 'var(--brand-800)',
          900: 'var(--brand-900)',
          950: 'var(--brand-950)',
          DEFAULT: 'var(--brand)',
          fg: 'var(--brand-fg)',
        },
      },
      fontSize: {
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        md: 'var(--text-md)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
      },
      zIndex: {
        base: 'var(--z-base)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        overlay: 'var(--z-overlay)',
        modal: 'var(--z-modal)',
        toast: 'var(--z-toast)',
        tour: 'var(--z-tour)',
      },
      fontFamily: {
        sans: ["var(--font-inter)", ...defaultTheme.fontFamily.sans],
        playfair: ["var(--font-playfair)", "serif"],
        document: ["var(--font-document)", "Georgia", "serif"],
        inter: ["var(--font-inter)", "sans-serif"],
      }
    },
  },
  plugins: [],
};

export default config;
