export const AGENT_REGISTRY = {
  "inbox-triage": {
    label: "Inbox Triage",
    description: "Summarizes workspace state when key events occur.",
    category: "operations",
    canDisable: true,
    defaultModelTier: "fast" as const,
    costTier: "low" as const,
    inputs: ["workspace state", "open actions/tensions/proposals"],
    outputs: ["operating state summary"],
  },
  "meeting-summary": {
    label: "Meeting Summary",
    description: "Generates concise summaries from meeting transcripts.",
    category: "knowledge",
    canDisable: false,
    defaultModelTier: "standard" as const,
    costTier: "medium" as const,
    inputs: ["meeting transcript"],
    outputs: ["summary markdown"],
  },
  "action-extraction": {
    label: "Action Extraction",
    description: "Extracts actions, tensions, and proposals from meetings.",
    category: "knowledge",
    canDisable: false,
    defaultModelTier: "standard" as const,
    costTier: "medium" as const,
    inputs: ["meeting transcript + summary"],
    outputs: ["proposed actions", "proposed tensions", "structural proposals"],
  },
  "proposal-drafting": {
    label: "Proposal Drafting",
    description: "Drafts governance proposals from operator prompts.",
    category: "governance",
    canDisable: true,
    defaultModelTier: "quality" as const,
    costTier: "medium" as const,
    inputs: ["operator prompt", "knowledge citations"],
    outputs: ["structured proposal draft"],
  },
  "constitution-update-trigger": {
    label: "Constitution Impact Analysis",
    description: "Evaluates if an approved proposal affects the constitution.",
    category: "governance",
    canDisable: true,
    defaultModelTier: "standard" as const,
    costTier: "low" as const,
    inputs: ["approved proposal"],
    outputs: ["impact assessment"],
  },
  "constitution-synthesis": {
    label: "Constitution Synthesis",
    description: "Synthesizes policy corpus into a 10-point constitution.",
    category: "governance",
    canDisable: true,
    defaultModelTier: "quality" as const,
    costTier: "high" as const,
    inputs: ["full policy corpus", "current constitution"],
    outputs: ["updated constitution markdown"],
  },
  "finance-reconciliation-prep": {
    label: "Finance Reconciliation Prep",
    description: "Summarizes unreconciled spends for finance review.",
    category: "finance",
    canDisable: true,
    defaultModelTier: "standard" as const,
    costTier: "medium" as const,
    inputs: ["paid/unreconciled spends"],
    outputs: ["reconciliation summary"],
  },
  "brain-absorb": {
    label: "Brain Absorb",
    description: "Absorbs new sources into wiki articles with cascading updates.",
    category: "knowledge",
    canDisable: false,
    defaultModelTier: "quality" as const,
    costTier: "high" as const,
    inputs: ["brain source content", "article index"],
    outputs: ["updated/created articles", "backlinks"],
  },
  "brain-maintenance": {
    label: "Brain Maintenance",
    description: "Weekly: stale detection, dead links, orphans, backlink rebuild.",
    category: "knowledge",
    canDisable: true,
    defaultModelTier: "none" as const,
    costTier: "free" as const,
    inputs: ["article corpus"],
    outputs: ["maintenance report"],
  },
  "daily-check-in": {
    label: "Daily Check-In",
    description: "Generates contextual check-in questions per member.",
    category: "people",
    canDisable: true,
    defaultModelTier: "fast" as const,
    costTier: "low" as const,
    inputs: ["member context"],
    outputs: ["check-in question"],
  },
  "advice-routing": {
    label: "Advice Routing",
    description: "Recommends advisors for proposals based on expertise.",
    category: "governance",
    canDisable: true,
    defaultModelTier: "fast" as const,
    costTier: "low" as const,
    inputs: ["proposal content"],
    outputs: ["advisor suggestions"],
  },
  "process-linting": {
    label: "Process Linting",
    description: "Checks if adequate advice was gathered before execution.",
    category: "governance",
    canDisable: true,
    defaultModelTier: "fast" as const,
    costTier: "low" as const,
    inputs: ["advice process records"],
    outputs: ["compliance score + warnings"],
  },
  "spend-submission": {
    label: "Spend Submission",
    description: "Creates and submits spend requests programmatically.",
    category: "finance",
    canDisable: true,
    defaultModelTier: "none" as const,
    costTier: "free" as const,
    inputs: ["amount, currency, category, description"],
    outputs: ["submitted spend request"],
  },
  "daily-digest": {
    label: "Daily Digest & Emails",
    description: "Generates org-wide digest, updates person profiles, sends personalized emails.",
    category: "knowledge",
    canDisable: true,
    defaultModelTier: "standard" as const,
    costTier: "very-high" as const,
    inputs: ["24h conversation history"],
    outputs: ["digest article", "person profile updates", "personalized emails"],
  },
  "slack-agent": {
    label: "Slack Agent",
    description: "Interprets plain Slack requests and creates or drafts bounded Corgtex work items.",
    category: "operations",
    canDisable: true,
    defaultModelTier: "standard" as const,
    costTier: "medium" as const,
    inputs: ["Slack prompt", "workspace context", "thread context"],
    outputs: ["Slack reply", "created Corgtex records"],
  },
  "crm-email-extraction": {
    label: "CRM Email Extraction",
    description: "Extracts structured qualification data from raw email replies.",
    category: "crm",
    canDisable: true,
    defaultModelTier: "standard" as const,
    costTier: "low" as const,
    inputs: ["raw email reply"],
    outputs: ["structured qualification fields"],
  },
  "crm-drip-followup": {
    label: "CRM Drip Follow-Up",
    description: "Generates and sends personalized follow-up emails to non-responding leads.",
    category: "crm",
    canDisable: true,
    defaultModelTier: "excellent" as const,
    costTier: "low" as const,
    inputs: ["lead context", "follow-up number"],
    outputs: ["personalized email"],
  },
  "crm-lead-enrichment": {
    label: "CRM Lead Enrichment",
    description: "Enriches a qualified CRM contact by searching the web and applying high-confidence data.",
    category: "crm",
    canDisable: true,
    defaultModelTier: "quality" as const,
    costTier: "medium" as const,
    inputs: ["contact email"],
    outputs: ["company description", "industry", "headquarters"],
  },
} as const;

export type RegisteredAgentKey = keyof typeof AGENT_REGISTRY;
