import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import { prisma } from "@corgtex/shared";
import { assertDemoCredentialsScoped, assertDemoWorkspaceDisconnected, revokeDemoCredentials } from "../../../scripts/lib/demo-credentials.mjs";

describe("demo legacy credential retirement", () => {
  it("revokes access and refresh credentials, consumes codes, and refuses credentials outside the target", async () => {
    const key = randomUUID();
    const workspace = await prisma.workspace.create({ data: { slug: `demo-retirement-${key}`, name: "Synthetic demo retirement" } });
    const other = await prisma.workspace.create({ data: { slug: `demo-other-${key}`, name: "Synthetic isolation sentinel" } });
    const user = await prisma.user.create({ data: { email: `demo-${key}@validation.example`, passwordHash: "unused" } });
    const expiresAt = new Date(Date.now() + 60_000);
    let clientId: string | undefined;
    let definitionId: string | undefined;
    try {
      const sso = await prisma.workspaceSsoConfig.create({ data: { workspaceId: workspace.id, provider: "GOOGLE", clientId: "synthetic", clientSecretEnc: "synthetic", allowedDomains: ["example.test"], isEnabled: true } });
      await expect(assertDemoWorkspaceDisconnected(prisma, workspace.id)).rejects.toThrow("external access");
      await prisma.workspaceSsoConfig.delete({ where: { id: sso.id } });
      const transcript = await prisma.meetingTranscriptSourceConnection.create({ data: { workspaceId: workspace.id, provider: "FATHOM", authMode: "WEBHOOK", webhookSecretEnc: "synthetic" } });
      await expect(assertDemoWorkspaceDisconnected(prisma, workspace.id)).rejects.toThrow("external access");
      await prisma.meetingTranscriptSourceConnection.delete({ where: { id: transcript.id } });
      const meeting = await prisma.meeting.create({ data: { workspaceId: workspace.id, title: "Synthetic scheduled recorder", source: "synthetic", recordedAt: new Date(), participantIds: [] } });
      const recording = await prisma.meetingRecording.create({ data: { workspaceId: workspace.id, meetingId: meeting.id, provider: "RECALL_AI", externalBotId: key, meetingUrl: "https://example.test", status: "SCHEDULED" } });
      await expect(assertDemoWorkspaceDisconnected(prisma, workspace.id)).rejects.toThrow("recording authority");
      await prisma.meetingRecording.delete({ where: { id: recording.id } });
      const billing = await prisma.workspaceBillingProfile.create({ data: { workspaceId: workspace.id, stripeCustomerId: `synthetic-${key}` } });
      await expect(assertDemoWorkspaceDisconnected(prisma, workspace.id)).rejects.toThrow("billing authority");
      await prisma.workspaceBillingProfile.delete({ where: { id: billing.id } });
      const anonymousAgent = await prisma.agentCredential.create({ data: { workspaceId: workspace.id, label: "Synthetic bootstrap", tokenHash: `bootstrap-${key}`, scopes: [] } });
      await expect(assertDemoWorkspaceDisconnected(prisma, workspace.id, [user.id])).rejects.toThrow("non-fixture credentials");
      await prisma.agentCredential.delete({ where: { id: anonymousAgent.id } });
      await assertDemoWorkspaceDisconnected(prisma, workspace.id);
      const app = await prisma.oAuthApp.create({ data: { workspaceId: workspace.id, clientId: key, clientSecret: "unused", name: "Synthetic legacy app", redirectUris: [], scopes: [] } });
      const client = await prisma.mcpOAuthClient.create({ data: { clientId: key, name: "Synthetic legacy client", redirectUris: [], scopes: [] } });
      clientId = client.id;
      const definition = await prisma.appDefinition.create({ data: { appKey: `retirement-${key}`, title: "Synthetic legacy installation" } });
      definitionId = definition.id;
      const installation = await prisma.appInstallation.create({ data: { workspaceId: workspace.id, appDefinitionId: definition.id } });
      const common = { workspaceId: workspace.id, userId: user.id, expiresAt, scopes: [] };
      const oauth = await prisma.oAuthAccessToken.create({ data: { ...common, appId: app.id, tokenHash: `oauth-${key}`, refreshHash: `oauth-refresh-${key}` } });
      const mcp = await prisma.mcpOAuthAccessToken.create({ data: { ...common, clientId: client.id, instanceSlug: "selfserve", tokenHash: `mcp-${key}`, refreshHash: `mcp-refresh-${key}` } });
      await prisma.oAuthAuthorizationCode.create({ data: { ...common, appId: app.id, code: `oauth-code-${key}`, redirectUri: "http://localhost" } });
      await prisma.mcpOAuthAuthorizationCode.create({ data: { ...common, clientId: client.id, instanceSlug: "selfserve", code: `mcp-code-${key}`, redirectUri: "http://localhost", codeChallenge: key, codeChallengeMethod: "S256" } });
      await prisma.session.create({ data: { userId: user.id, tokenHash: `session-${key}`, expiresAt } });
      const session = await prisma.appSession.create({ data: { workspaceId: workspace.id, appInstallationId: installation.id, actorUserId: user.id, audience: "synthetic", tokenHash: `app-${key}`, expiresAt } });
      const credential = await prisma.agentCredential.create({ data: { workspaceId: workspace.id, createdByUserId: user.id, label: "Synthetic legacy credential", tokenHash: `agent-${key}`, scopes: [] } });
      const outside = await prisma.agentCredential.create({ data: { workspaceId: other.id, createdByUserId: user.id, label: "Synthetic sentinel credential", tokenHash: `outside-${key}`, scopes: [] } });
      await expect(assertDemoCredentialsScoped(prisma, workspace.id, [user.id])).rejects.toThrow("outside");
      expect((await prisma.oAuthAccessToken.findUniqueOrThrow({ where: { id: oauth.id } })).revokedAt).toBeNull();
      expect((await prisma.agentCredential.findUniqueOrThrow({ where: { id: outside.id } })).isActive).toBe(true);
      await prisma.agentCredential.delete({ where: { id: outside.id } });
      const ssoIdentity = await prisma.userSsoIdentity.create({ data: { userId: user.id, provider: "GOOGLE", providerSubjectId: key, email: user.email } });
      await expect(assertDemoCredentialsScoped(prisma, workspace.id, [user.id])).rejects.toThrow("personal SSO");
      await prisma.userSsoIdentity.delete({ where: { id: ssoIdentity.id } });
      const external = await prisma.externalMcpConnection.create({ data: { workspaceId: workspace.id, userId: user.id, providerKey: "synthetic", displayName: "Synthetic provider", serverUrl: "https://example.test", accessTokenEnc: "synthetic" } });
      await expect(assertDemoCredentialsScoped(prisma, workspace.id, [user.id])).rejects.toThrow("personal provider");
      await prisma.externalMcpConnection.delete({ where: { id: external.id } });
      const support = await prisma.workspaceSupportGrant.create({ data: { workspaceId: other.id, userId: user.id, grantedByUserId: user.id, role: "SETUP" } });
      await expect(assertDemoCredentialsScoped(prisma, workspace.id, [user.id])).rejects.toThrow("support access");
      await prisma.workspaceSupportGrant.delete({ where: { id: support.id } });
      await assertDemoCredentialsScoped(prisma, workspace.id, [user.id]);
      await revokeDemoCredentials(prisma, workspace.id, [user.id]);
      expect((await prisma.oAuthAccessToken.findUniqueOrThrow({ where: { id: oauth.id } })).revokedAt).not.toBeNull();
      expect((await prisma.mcpOAuthAccessToken.findUniqueOrThrow({ where: { id: mcp.id } })).revokedAt).not.toBeNull();
      expect((await prisma.appSession.findUniqueOrThrow({ where: { id: session.id } })).revokedAt).not.toBeNull();
      expect((await prisma.agentCredential.findUniqueOrThrow({ where: { id: credential.id } })).isActive).toBe(false);
      expect(await prisma.oAuthAuthorizationCode.count({ where: { userId: user.id } })).toBe(0);
      expect(await prisma.mcpOAuthAuthorizationCode.count({ where: { userId: user.id } })).toBe(0);
      expect(await prisma.session.count({ where: { userId: user.id } })).toBe(0);
      expect((await prisma.oAuthApp.findUniqueOrThrow({ where: { id: app.id } })).isActive).toBe(false);
    } finally {
      await prisma.oAuthAccessToken.deleteMany({ where: { workspaceId: workspace.id } });
      await prisma.workspace.deleteMany({ where: { id: { in: [workspace.id, other.id] } } });
      await prisma.user.delete({ where: { id: user.id } });
      if (clientId) await prisma.mcpOAuthClient.delete({ where: { id: clientId } });
      if (definitionId) await prisma.appDefinition.delete({ where: { id: definitionId } });
    }
  });
});
