import type { AgentScope } from "./agent-auth";

export type McpToolCapability = {
  scopes: readonly AgentScope[];
  destructive?: boolean;
  sensitive?: boolean;
};

export const MCP_TOOL_CAPABILITIES = {
  chat: { scopes: ["conversations:write"] },
  search_knowledge: { scopes: ["brain:read"] },
  query_context_graph: { scopes: ["context-graph:read"] },
  get_context_neighbors: { scopes: ["context-graph:read"] },
  get_context_evidence: { scopes: ["context-graph:read"] },
  get_selected_region_context: { scopes: ["context-graph:read"] },
  get_context_graph_map_schema: { scopes: ["context-graph:read"] },
  create_context_graph_proposed_diff: { scopes: ["context-graph:propose"] },
  import_context_graph_map: { scopes: ["context-graph:approve"], sensitive: true },
  search: { scopes: ["brain:read"] },
  fetch: { scopes: ["brain:read"] },
  list_connected_tools: { scopes: ["external-tools:read"] },
  list_installed_apps: { scopes: ["tools:read"] },
  get_app_routing_guidance: { scopes: ["tools:read"] },
  get_app_connection_instructions: { scopes: ["tools:read"] },
  invoke_installed_app_tool: { scopes: ["tools:write"] },
  request_app_install: { scopes: ["tools:write"] },
  search_connected_context: { scopes: ["external-tools:read"] },
  fetch_connected_context: { scopes: ["external-tools:read"] },
  execute_external_tool: { scopes: ["external-tools:write"] },
  get_current_connection: { scopes: ["workspace:read"] },
  get_workspace_info: { scopes: ["workspace:read"] },
  daily_overview: { scopes: ["workspace:read", "actions:read", "proposals:read", "tensions:read", "meetings:read", "finance:read"] },
  create_execution_request: { scopes: ["execution:write"] },
  get_execution_packet: { scopes: ["execution:read"] },
  get_company_context: { scopes: ["execution:read", "workspace:read", "actions:read", "tensions:read", "proposals:read", "meetings:read", "brain:read"] },
  list_writeback_targets: { scopes: ["execution:read"] },
  submit_execution_result: { scopes: ["execution:write"] },
  list_relationship_accounts: { scopes: ["relationships:read"] },
  get_relationship_account: { scopes: ["relationships:read"] },
  list_relationship_contacts: { scopes: ["relationships:read"] },
  list_relationship_deals: { scopes: ["relationships:read"] },
  list_due_relationship_work: { scopes: ["relationships:read"] },
  list_communication_suggestions: { scopes: ["relationships:read"] },
  record_relationship_activity: { scopes: ["relationships:write"] },
  complete_relationship_activity: { scopes: ["relationships:write"] },
  create_communication_suggestion: { scopes: ["relationships:write"] },
  complete_communication_suggestion: { scopes: ["relationships:write"] },
  record_support_audit: { scopes: ["support:write"], sensitive: true },
  list_integrations: { scopes: ["integrations:read"] },
  list_data_sources: { scopes: ["data-sources:read"] },
  sync_data_source: { scopes: ["data-sources:write"] },
  list_tool_links: { scopes: ["tools:read"] },
  upsert_tool_link: { scopes: ["tools:write"] },
  reveal_tool_link_credential: { scopes: ["tools:credentials:read"], sensitive: true },
  archive_tool_link: { scopes: ["tools:write"] },
  list_agent_runs: { scopes: ["agents:read"] },
  list_agent_credentials: { scopes: ["agents:read"] },
  update_agent_credential_scopes: { scopes: ["support:write"], sensitive: true },
  revoke_agent_credential: { scopes: ["support:write"], destructive: true, sensitive: true },
  list_agent_configs: { scopes: ["agents:read"] },
  get_newspaper_diagnostics: { scopes: ["agents:read", "runtime:read"] },
  update_agent_policy: { scopes: ["support:write"], sensitive: true },
  get_model_budget: { scopes: ["agents:read"] },
  update_model_budget: { scopes: ["support:write"], sensitive: true },
  list_runtime_jobs: { scopes: ["runtime:read"] },
  list_failed_jobs: { scopes: ["runtime:read"] },
  retry_failed_job: { scopes: ["runtime:write"] },
  discard_failed_job: { scopes: ["runtime:write"] },
  upload_document_text: { scopes: ["documents:write"] },
  list_proposals: { scopes: ["proposals:read"] },
  get_proposal: { scopes: ["proposals:read"] },
  list_proposal_comments: { scopes: ["proposals:read"] },
  post_proposal_comment: { scopes: ["proposals:write"] },
  resolve_proposal_comment: { scopes: ["proposals:write"] },
  create_proposal: { scopes: ["proposals:write"] },
  update_proposal: { scopes: ["proposals:write"] },
  resolve_proposal: { scopes: ["proposals:write"] },
  submit_proposal: { scopes: ["proposals:write"] },
  archive_proposal: { scopes: ["proposals:write"] },
  publish_proposal: { scopes: ["proposals:write"] },
  return_proposal_to_draft: { scopes: ["proposals:write"] },
  support_reopen_resolved_proposals: { scopes: ["support:write", "proposals:write"], sensitive: true },
  list_actions: { scopes: ["actions:read"] },
  create_action: { scopes: ["actions:write"] },
  update_action: { scopes: ["actions:write"] },
  complete_action: { scopes: ["actions:write"] },
  return_action_to_draft: { scopes: ["actions:write"] },
  delete_action: { scopes: ["actions:write"] },
  list_tensions: { scopes: ["tensions:read"] },
  create_tension: { scopes: ["tensions:write"] },
  update_tension: { scopes: ["tensions:write"] },
  return_tension_to_draft: { scopes: ["tensions:write"] },
  upvote_tension: { scopes: ["tensions:write"] },
  list_tension_comments: { scopes: ["tensions:read"] },
  post_tension_comment: { scopes: ["tensions:write"] },
  resolve_tension_comment: { scopes: ["tensions:write"] },
  delete_tension: { scopes: ["tensions:write"] },
  list_goals: { scopes: ["goals:read"] },
  get_goal: { scopes: ["goals:read"] },
  create_goal: { scopes: ["goals:write"] },
  update_goal: { scopes: ["goals:write"] },
  return_goal_to_draft: { scopes: ["goals:write"] },
  archive_goal: { scopes: ["goals:write"] },
  list_members: { scopes: ["members:read"] },
  create_member: { scopes: ["members:write"] },
  update_member: { scopes: ["members:write"] },
  deactivate_member: { scopes: ["members:write"] },
  resend_member_access_link: { scopes: ["members:write"] },
  list_feature_flags: { scopes: ["workspace:read"] },
  set_feature_flag: { scopes: ["workspace:write"] },
  list_meetings: { scopes: ["meetings:read"] },
  get_meeting: { scopes: ["meetings:read"] },
  get_meeting_recorder_coverage_readiness: { scopes: ["meetings:read"] },
  set_meeting_series_recorder_url: { scopes: ["meetings:write", "support:write"], sensitive: true },
  set_meeting_recorder_auto_recording: { scopes: ["meetings:write", "support:write"], sensitive: true },
  ensure_meeting_recorder_coverage: { scopes: ["meetings:write", "support:write"], sensitive: true },
  upload_meeting: { scopes: ["meetings:write"] },
  delete_meeting: { scopes: ["meetings:write"] },
  list_articles: { scopes: ["brain:read"] },
  get_article: { scopes: ["brain:read"] },
  create_article: { scopes: ["brain:write"] },
  update_article: { scopes: ["brain:write"] },
  delete_article: { scopes: ["brain:write"] },
  publish_article: { scopes: ["brain:write"] },
  return_article_to_draft: { scopes: ["brain:write"] },
  create_discussion_thread: { scopes: ["brain:write"] },
  add_discussion_comment: { scopes: ["brain:write"] },
  resolve_discussion: { scopes: ["brain:write"] },
  list_cycles: { scopes: ["cycles:read"] },
  get_cycle: { scopes: ["cycles:read"] },
  list_cycle_updates: { scopes: ["cycles:read"] },
  list_allocations: { scopes: ["cycles:read"] },
  create_cycle: { scopes: ["cycles:write"] },
  update_cycle: { scopes: ["cycles:write"] },
  list_circles: { scopes: ["circles:read"] },
  get_constitution: { scopes: ["governance:read"] },
  list_policies: { scopes: ["governance:read"] },
  list_approval_policies: { scopes: ["governance:read"] },
  archive_artifact: { scopes: ["archive:write"] },
  list_archived_artifacts: { scopes: ["archive:read"] },
  restore_artifact: { scopes: ["archive:write"] },
  purge_artifact: { scopes: ["archive:write"], destructive: true },
  list_work_item_versions: { scopes: [] },
  get_work_item_version: { scopes: [] },
} as const satisfies Record<string, McpToolCapability>;

export type McpToolName = keyof typeof MCP_TOOL_CAPABILITIES;

export function hasMcpToolCapability(name: string): name is McpToolName {
  return Object.prototype.hasOwnProperty.call(MCP_TOOL_CAPABILITIES, name);
}

export function getMcpToolCapability(name: string): McpToolCapability | null {
  return hasMcpToolCapability(name) ? MCP_TOOL_CAPABILITIES[name] : null;
}

export function getRequiredScopesForMcpTool(name: string): AgentScope[] {
  const capability = getMcpToolCapability(name);
  return capability ? [...capability.scopes] : [];
}
