import type { AgentRunStatus, AgentTriggerType } from "@prisma/client";
import { Prisma } from "@prisma/client";
import { createConstitutionVersion, type AgentKey } from "@corgtex/domain";
import { env, prisma, toInputJson } from "@corgtex/shared";
import { searchIndexedKnowledge } from "@corgtex/knowledge";
import { defaultModelGateway, resolveModel } from "@corgtex/models";
import { absorbSource } from "./brain-absorb";
import { runBrainMaintenance } from "./brain-maintenance";
import { isAgentEnabled, getAgentModelOverride, AGENT_REGISTRY, type RegisteredAgentKey } from "@corgtex/domain";

type AgentOutcome = {
  resultJson: Prisma.InputJsonValue;
  approvalCheckpoint?: {
    summary: string;
    detail: Prisma.InputJsonValue;
  };
};

type AgentHelpers = {
  step<T>(name: string, input: unknown, work: () => Promise<T>): Promise<T>;
  tool<T>(name: string, input: unknown, work: () => Promise<T>): Promise<T>;
};

type AgentRunParams<TPayload extends Record<string, unknown>, TContext extends Record<string, unknown>> = {
  agentKey: AgentKey;
  workspaceId: string;
  triggerType: AgentTriggerType;
  triggerRef: string;
  goal: string;
  payload: TPayload;
  plan: string[];
  buildContext: (helpers: AgentHelpers, runId: string) => Promise<TContext>;
  execute: (context: TContext, helpers: AgentHelpers, runId: string, model: string) => Promise<AgentOutcome>;
};

function toJson(value: unknown): Prisma.InputJsonValue {
  return toInputJson(value);
}

function serializeError(error: unknown) {
  return error instanceof Error ? error.message : "Unknown agent runtime error.";
}

function asString(value: unknown) {
  return typeof value === "string" ? value.trim() : "";
}

function normalizeActionDrafts(value: unknown) {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((entry) => {
      if (!entry || typeof entry !== "object") {
        return null;
      }

      const record = entry as Record<string, unknown>;
      const title = asString(record.title);
      if (!title) {
        return null;
      }

      return {
        title,
        rationale: asString(record.rationale) || null,
      };
    })
    .filter((entry): entry is { title: string; rationale: string | null } => Boolean(entry));
}

function normalizeProposalDraft(value: Record<string, unknown>, fallbackPrompt: string) {
  const title = asString(value.title) || fallbackPrompt.slice(0, 80) || "Draft proposal";
  const summary = asString(value.summary) || null;
  const bodyMd = asString(value.bodyMd) || asString(value.body) || `# ${title}\n\n${summary ?? "Proposal draft generated by agent."}`;

  return {
    title,
    summary,
    bodyMd,
  };
}

async function currentAgentRunCount(workspaceId: string) {
  return prisma.agentRun.count({
    where: {
      workspaceId,
      status: {
        in: ["PENDING", "RUNNING"],
      },
    },
  });
}

async function findExistingRun(agentKey: AgentKey, workspaceId: string, triggerType: AgentTriggerType, triggerRef: string) {
  return prisma.agentRun.findFirst({
    where: {
      workspaceId,
      agentKey,
      triggerType,
      triggerRef,
    },
    orderBy: {
      createdAt: "desc",
    },
  });
}

async function executeAgentRun<TPayload extends Record<string, unknown>, TContext extends Record<string, unknown>>(
  params: AgentRunParams<TPayload, TContext>,
) {
  const existing = await findExistingRun(params.agentKey, params.workspaceId, params.triggerType, params.triggerRef);
  if (existing && existing.status !== "FAILED" && existing.status !== "CANCELLED") {
    return existing;
  }

  const isEnabled = await isAgentEnabled(params.workspaceId, params.agentKey);
  if (!isEnabled) {
    return { skipped: true, reason: "agent_disabled" };
  }

  if (env.AGENT_KILL_SWITCH) {
    return { skipped: true, reason: "kill_switch" };
  }

  const running = await currentAgentRunCount(params.workspaceId);
  if (running >= env.WORKSPACE_AGENT_MAX_CONCURRENCY) {
    return { skipped: true, reason: "concurrency_limit" };
  }

  const { checkBudget } = await import("@corgtex/domain");
  const budget = await checkBudget(params.workspaceId);
  if (!budget.allowed) {
    return { skipped: true, reason: "budget_exceeded" };
  }

  const run = await prisma.agentRun.create({
    data: {
      workspaceId: params.workspaceId,
      agentKey: params.agentKey,
      triggerType: params.triggerType,
      triggerRef: params.triggerRef,
      status: "RUNNING",
      goal: params.goal,
      planJson: toJson({
        steps: params.plan,
        payload: params.payload,
      }),
      startedAt: new Date(),
      contextJson: {},
    },
  });

  const accumulatedSteps: Prisma.AgentStepCreateManyInput[] = [];
  const accumulatedToolCalls: Prisma.AgentToolCallCreateManyInput[] = [];

  const helpers: AgentHelpers = {
    async step<T>(name: string, input: unknown, work: () => Promise<T>) {
      const startedAt = new Date();
      try {
        const output = await work();
        accumulatedSteps.push({
          agentRunId: run.id,
          name,
          status: "COMPLETED",
          inputJson: toJson(input) as any,
          outputJson: toJson(output) as any,
          startedAt,
          completedAt: new Date(),
          error: null,
        });
        return output;
      } catch (error) {
        accumulatedSteps.push({
          agentRunId: run.id,
          name,
          status: "FAILED",
          inputJson: toJson(input) as any,
          outputJson: Prisma.DbNull,
          startedAt,
          completedAt: new Date(),
          error: serializeError(error),
        });
        throw error;
      }
    },

    async tool<T>(name: string, input: unknown, work: () => Promise<T>) {
      const startedAt = new Date();
      try {
        const output = await work();
        accumulatedToolCalls.push({
          agentRunId: run.id,
          name,
          status: "COMPLETED",
          inputJson: toJson(input) as any,
          outputJson: toJson(output) as any,
          startedAt,
          completedAt: new Date(),
          error: null,
        });
        return output;
      } catch (error) {
        accumulatedToolCalls.push({
          agentRunId: run.id,
          name,
          status: "FAILED",
          inputJson: toJson(input) as any,
          outputJson: Prisma.DbNull,
          startedAt,
          completedAt: new Date(),
          error: serializeError(error),
        });
        throw error;
      }
    },
  };

  try {
    const override = await getAgentModelOverride(params.workspaceId, params.agentKey);
    const tier = AGENT_REGISTRY[params.agentKey as RegisteredAgentKey]?.defaultModelTier ?? "none";
    const model = resolveModel(tier, override);

    const context = await helpers.step("load-context", params.payload, () => params.buildContext(helpers, run.id));
    const outcome = await params.execute(context, helpers, run.id, model);
    const nextStatus: AgentRunStatus = outcome.approvalCheckpoint ? "WAITING_APPROVAL" : "COMPLETED";

    const finalRun = await prisma.$transaction(async (tx) => {
      if (accumulatedSteps.length > 0) {
        await tx.agentStep.createMany({ data: accumulatedSteps });
      }
      if (accumulatedToolCalls.length > 0) {
        await tx.agentToolCall.createMany({ data: accumulatedToolCalls });
      }

      const updated = await tx.agentRun.update({
        where: { id: run.id },
        data: {
          status: nextStatus,
          approvalRequired: Boolean(outcome.approvalCheckpoint),
          resultJson: toJson({
            ...((outcome.resultJson as Record<string, unknown>) ?? {}),
            approvalCheckpoint: outcome.approvalCheckpoint ?? null,
          }),
          contextJson: toJson(context),
          completedAt: nextStatus === "COMPLETED" ? new Date() : null,
          failedAt: null,
        },
      });

      await tx.event.create({
        data: {
          workspaceId: params.workspaceId,
          type: `agent.run.${nextStatus === "COMPLETED" ? "completed" : "waiting_approval"}`,
          aggregateType: "agentRun",
          aggregateId: updated.id,
          payload: toJson({
            agentKey: params.agentKey,
            goal: params.goal,
            status: nextStatus,
            resultJson: outcome.resultJson,
          }),
        },
      });

      return updated;
    });

    return finalRun;
  } catch (error) {
    const failedRun = await prisma.$transaction(async (tx) => {
      if (accumulatedSteps.length > 0) {
        await tx.agentStep.createMany({ data: accumulatedSteps });
      }
      if (accumulatedToolCalls.length > 0) {
        await tx.agentToolCall.createMany({ data: accumulatedToolCalls });
      }

      const updated = await tx.agentRun.update({
        where: { id: run.id },
        data: {
          status: "FAILED",
          approvalRequired: false,
          resultJson: toJson({
            error: serializeError(error),
          }),
          failedAt: new Date(),
        },
      });

      await tx.event.create({
        data: {
          workspaceId: params.workspaceId,
          type: "agent.run.failed",
          aggregateType: "agentRun",
          aggregateId: updated.id,
          payload: toJson({
            agentKey: params.agentKey,
            goal: params.goal,
            status: "FAILED",
            error: serializeError(error),
          }),
        },
      });

      return updated;
    });

    throw error;
  }
}


export async function runInboxTriageAgent(params: {
  workspaceId: string;
  triggerRef: string;
  triggerType?: AgentTriggerType;
}) {
  return executeAgentRun({
    agentKey: "inbox-triage",
    workspaceId: params.workspaceId,
    triggerType: params.triggerType ?? "EVENT",
    triggerRef: params.triggerRef,
    goal: "Triage workspace inbox and summarize current operating state.",
    payload: {},
    plan: ["load-context", "summarize-inbox"],
    buildContext: (helpers) => helpers.tool("workspace.snapshot", {}, async () => {
      const [openActions, openTensions, submittedProposals] = await Promise.all([
        prisma.action.count({
          where: {
            workspaceId: params.workspaceId,
            status: {
              in: ["OPEN", "IN_PROGRESS"],
            },
          },
        }),
        prisma.tension.count({
          where: {
            workspaceId: params.workspaceId,
            status: {
              in: ["OPEN", "IN_PROGRESS"],
            },
          },
        }),
        prisma.proposal.count({
          where: {
            workspaceId: params.workspaceId,
            status: "SUBMITTED",
          },
        }),
      ]);

      return {
        openActions,
        openTensions,
        submittedProposals,
      };
    }),
    execute: async (context, helpers, runId, model) => {
      const summary = await helpers.tool("model.chat", { purpose: "workspace-triage" }, async () => defaultModelGateway.chat({ model,
        workspaceId: params.workspaceId,
        agentRunId: runId,
        taskType: "AGENT",
        messages: [
          {
            role: "system",
            content: "Summarize the workspace operating state for an internal operator inbox.",
          },
          {
            role: "user",
            content: JSON.stringify(context),
          },
        ],
      }));

      return {
        resultJson: {
          summary: summary.content,
          metrics: context,
        },
      };
    },
  });
}

export async function runMeetingSummaryAgent(params: {
  workspaceId: string;
  triggerRef: string;
  meetingId: string;
  triggerType?: AgentTriggerType;
}) {
  return executeAgentRun({
    agentKey: "meeting-summary",
    workspaceId: params.workspaceId,
    triggerType: params.triggerType ?? "EVENT",
    triggerRef: params.triggerRef,
    goal: "Summarize meeting content and persist an operator-readable digest.",
    payload: {
      meetingId: params.meetingId,
    },
    plan: ["load-context", "generate-summary", "persist-summary"],
    buildContext: (helpers) => helpers.tool("meeting.load", { meetingId: params.meetingId }, async () => prisma.meeting.findUnique({
      where: { id: params.meetingId },
      select: {
        id: true,
        workspaceId: true,
        title: true,
        source: true,
        transcript: true,
        summaryMd: true,
        recordedAt: true,
      },
    }).then((meeting) => ({
      meeting,
    }))),
    execute: async (context, helpers, runId, model) => {
      const meeting = context.meeting as {
        id: string;
        workspaceId: string;
        title: string | null;
        source: string;
        transcript: string | null;
        summaryMd: string | null;
        recordedAt: string | Date;
      } | null;

      if (!meeting || meeting.workspaceId !== params.workspaceId) {
        return {
          resultJson: {
            skipped: true,
            reason: "missing_meeting",
          },
        };
      }

      const summary = await helpers.tool("model.chat", { meetingId: meeting.id }, async () => defaultModelGateway.chat({ model,
        workspaceId: params.workspaceId,
        agentRunId: runId,
        taskType: "SUMMARY",
        messages: [
          {
            role: "system",
            content: "Summarize this meeting for an operator dashboard. Keep it concise, factual, and action-oriented.",
          },
          {
            role: "user",
            content: JSON.stringify({
              title: meeting.title,
              source: meeting.source,
              recordedAt: meeting.recordedAt,
              transcript: meeting.transcript,
              currentSummary: meeting.summaryMd,
            }),
          },
        ],
      }));

      await helpers.step("persist-summary", { meetingId: meeting.id }, async () => prisma.meeting.update({
        where: { id: meeting.id },
        data: {
          summaryMd: summary.content,
        },
      }));

      return {
        resultJson: {
          meetingId: meeting.id,
          summary: summary.content,
        },
      };
    },
  });
}

export async function runActionExtractionAgent(params: {
  workspaceId: string;
  triggerRef: string;
  meetingId: string;
  triggerType?: AgentTriggerType;
}) {
  return executeAgentRun({
    agentKey: "action-extraction",
    workspaceId: params.workspaceId,
    triggerType: params.triggerType ?? "EVENT",
    triggerRef: params.triggerRef,
    goal: "Extract proposed action items, structural proposals, and tensions from meeting content and pause for approval before creating records.",
    payload: {
      meetingId: params.meetingId,
    },
    plan: ["load-context", "extract-actions", "approval-checkpoint"],
    buildContext: (helpers) => helpers.tool("meeting.load", { meetingId: params.meetingId }, async () => prisma.meeting.findUnique({
      where: { id: params.meetingId },
      select: {
        id: true,
        workspaceId: true,
        title: true,
        transcript: true,
        summaryMd: true,
      },
    }).then((meeting) => ({
      meeting,
    }))),
    execute: async (context, helpers, runId, model) => {
      const meeting = context.meeting as {
        id: string;
        workspaceId: string;
        title: string | null;
        transcript: string | null;
        summaryMd: string | null;
      } | null;

      if (!meeting || meeting.workspaceId !== params.workspaceId) {
        return {
          resultJson: {
            skipped: true,
            reason: "missing_meeting",
          },
        };
      }

      const extracted = await helpers.tool("model.extract", { meetingId: meeting.id }, async () => defaultModelGateway.extract({ model,
        workspaceId: params.workspaceId,
        agentRunId: runId,
        instruction: "Extract concrete follow-up actions, systemic tensions, and structural proposals (e.g. role changes or new accountabilities) discussed in this meeting.",
        schemaHint: "{ actions: [{ title: string, rationale: string }], tensions: [{ title: string, description: string }], proposals: [{ title: string, type: string, description: string }] }",
        input: JSON.stringify({
          title: meeting.title,
          summary: meeting.summaryMd,
          transcript: meeting.transcript,
        }),
      }));

      const proposedActions = normalizeActionDrafts(extracted.output?.actions || []);
      const proposedTensions = Array.isArray(extracted.output?.tensions) ? extracted.output.tensions : [];
      const structuralProposals = Array.isArray(extracted.output?.proposals) ? extracted.output.proposals : [];

      return {
        resultJson: {
          meetingId: meeting.id,
          proposedActions,
          proposedTensions,
          structuralProposals,
        },
        approvalCheckpoint: {
          summary: "Review extracted actions, tensions, and structural proposals before creating records.",
          detail: {
            meetingId: meeting.id,
            proposedActions,
            proposedTensions,
            structuralProposals,
          },
        },
      };
    },
  });
}

export async function runProposalDraftingAgent(params: {
  workspaceId: string;
  triggerRef: string;
  prompt: string;
  meetingId?: string | null;
  triggerType?: AgentTriggerType;
}) {
  return executeAgentRun({
    agentKey: "proposal-drafting",
    workspaceId: params.workspaceId,
    triggerType: params.triggerType ?? "MANUAL",
    triggerRef: params.triggerRef,
    goal: "Draft a proposal from operator guidance and indexed workspace knowledge, then pause for approval.",
    payload: {
      prompt: params.prompt,
      meetingId: params.meetingId ?? null,
    },
    plan: ["load-context", "search-knowledge", "draft-proposal", "structure-draft", "approval-checkpoint"],
    buildContext: async (helpers, runId) => {
      const citations = await helpers.tool("knowledge.search", { prompt: params.prompt }, () => searchIndexedKnowledge({
        workspaceId: params.workspaceId,
        agentRunId: runId,
        query: params.prompt,
        limit: 4,
      }));

      let meeting: {
        id: string;
        title: string | null;
        summaryMd: string | null;
        transcript: string | null;
      } | null = null;

      if (params.meetingId) {
        meeting = await helpers.tool("meeting.load", { meetingId: params.meetingId }, async () => prisma.meeting.findUnique({
          where: { id: params.meetingId! },
          select: {
            id: true,
            title: true,
            summaryMd: true,
            transcript: true,
          },
        }));
      }

      return {
        citations,
        meeting,
      };
    },
    execute: async (context, helpers, runId, model) => {
      const citations = Array.isArray(context.citations) ? context.citations : [];
      const draft = await helpers.tool("model.chat", { prompt: params.prompt }, async () => defaultModelGateway.chat({ model,
        workspaceId: params.workspaceId,
        agentRunId: runId,
        taskType: "AGENT",
        messages: [
          {
            role: "system",
            content: "Draft a workspace proposal. Use the indexed context when available and produce markdown with a clear title, summary, and body.",
          },
          {
            role: "user",
            content: JSON.stringify({
              prompt: params.prompt,
              meeting: context.meeting ?? null,
              citations,
            }),
          },
        ],
      }));

      const structured = await helpers.tool("model.extract", { prompt: params.prompt }, async () => defaultModelGateway.extract({ model,
        workspaceId: params.workspaceId,
        agentRunId: runId,
        instruction: "Convert this proposal draft into a structured proposal payload.",
        schemaHint: "{ title: string, summary: string, bodyMd: string }",
        input: draft.content,
      }));

      const proposalDraft = normalizeProposalDraft(structured.output, params.prompt);

      return {
        resultJson: {
          prompt: params.prompt,
          citations,
          proposalDraft,
        },
        approvalCheckpoint: {
          summary: "Review the drafted proposal before creating a proposal record.",
          detail: {
            prompt: params.prompt,
            citations,
            proposalDraft,
          },
        },
      };
    },
  });
}

export async function runConstitutionUpdateTriggerAgent(params: {
  workspaceId: string;
  triggerRef: string;
  proposalId: string;
  triggerType?: AgentTriggerType;
}) {
  return executeAgentRun({
    agentKey: "constitution-update-trigger",
    workspaceId: params.workspaceId,
    triggerType: params.triggerType ?? "EVENT",
    triggerRef: params.triggerRef,
    goal: "Review whether an approved proposal should trigger constitution or policy follow-up.",
    payload: {
      proposalId: params.proposalId,
    },
    plan: ["load-context", "summarize-impact", "approval-checkpoint"],
    buildContext: (helpers) => helpers.tool("proposal.load", { proposalId: params.proposalId }, async () => {
      const [proposal, policyCorpus] = await Promise.all([
        prisma.proposal.findUnique({
          where: { id: params.proposalId },
          select: {
            id: true,
            workspaceId: true,
            title: true,
            summary: true,
            bodyMd: true,
            status: true,
          },
        }),
        prisma.policyCorpus.findUnique({
          where: { proposalId: params.proposalId },
          select: {
            id: true,
            title: true,
            bodyMd: true,
            acceptedAt: true,
          },
        }),
      ]);

      return {
        proposal,
        policyCorpus,
      };
    }),
    execute: async (context, helpers, runId, model) => {
      const proposal = context.proposal as {
        id: string;
        workspaceId: string;
        title: string;
        summary: string | null;
        bodyMd: string;
        status: string;
      } | null;

      if (!proposal || proposal.workspaceId !== params.workspaceId) {
        return {
          resultJson: {
            skipped: true,
            reason: "missing_proposal",
          },
        };
      }

      const impact = await helpers.tool("model.chat", { proposalId: proposal.id }, async () => defaultModelGateway.chat({ model,
        workspaceId: params.workspaceId,
        agentRunId: runId,
        taskType: "AGENT",
        messages: [
          {
            role: "system",
            content: "Assess whether this approved proposal should trigger constitution or policy follow-up. Keep the output concise and operational.",
          },
          {
            role: "user",
            content: JSON.stringify({
              proposal,
              policyCorpus: context.policyCorpus ?? null,
            }),
          },
        ],
      }));

      return {
        resultJson: {
          proposalId: proposal.id,
          impactSummary: impact.content,
        },
        approvalCheckpoint: {
          summary: "Review the suggested constitution or policy follow-up before taking protected action.",
          detail: {
            proposalId: proposal.id,
            impactSummary: impact.content,
          },
        },
      };
    },
  });
}

export async function runFinanceReconciliationPrepAgent(params: {
  workspaceId: string;
  triggerRef: string;
  spendId?: string | null;
  triggerType?: AgentTriggerType;
}) {
  return executeAgentRun({
    agentKey: "finance-reconciliation-prep",
    workspaceId: params.workspaceId,
    triggerType: params.triggerType ?? (params.spendId ? "EVENT" : "MANUAL"),
    triggerRef: params.triggerRef,
    goal: "Prepare reconciliation notes for paid spends that still need finance review.",
    payload: {
      spendId: params.spendId ?? null,
    },
    plan: ["load-context", "summarize-finance-state"],
    buildContext: (helpers) => helpers.tool("finance.unreconciled-spends", { spendId: params.spendId ?? null }, async () => {
      const spends = await prisma.spendRequest.findMany({
        where: {
          workspaceId: params.workspaceId,
          status: "PAID",
          reconciliationStatus: {
            not: "RECONCILED",
          },
          ...(params.spendId ? { id: params.spendId } : {}),
        },
        include: {
          ledgerAccount: {
            select: {
              id: true,
              name: true,
              currency: true,
            },
          },
          proposalLinks: {
            include: {
              proposal: {
                select: {
                  id: true,
                  title: true,
                  status: true,
                },
              },
            },
          },
        },
        orderBy: { updatedAt: "desc" },
        take: 10,
      });

      return {
        spends,
      };
    }),
    execute: async (context, helpers, runId, model) => {
      const spends = Array.isArray(context.spends) ? context.spends : [];
      if (spends.length === 0) {
        return {
          resultJson: {
            summary: "No paid unreconciled spends need preparation.",
            spendIds: [],
          },
        };
      }

      const summary = await helpers.tool("model.chat", { spendCount: spends.length }, async () => defaultModelGateway.chat({ model,
        workspaceId: params.workspaceId,
        agentRunId: runId,
        taskType: "SUMMARY",
        messages: [
          {
            role: "system",
            content: "Summarize the reconciliation work needed for these paid spends. Keep the output concise and finance-oriented.",
          },
          {
            role: "user",
            content: JSON.stringify(spends),
          },
        ],
      }));

      return {
        resultJson: {
          summary: summary.content,
          spendIds: spends.map((spend) => spend.id),
        },
      };
    },
  });
}

export async function runConstitutionSynthesisAgent(params: {
  workspaceId: string;
  triggerRef: string;
  triggerType?: AgentTriggerType;
}) {
  return executeAgentRun({
    agentKey: "constitution-synthesis",
    workspaceId: params.workspaceId,
    triggerType: params.triggerType ?? "EVENT",
    triggerRef: params.triggerRef,
    goal: "Synthesize current policy corpus into an updated constitution document.",
    payload: {},
    plan: ["load-context", "synthesize-constitution", "persist-version"],
    buildContext: (helpers) => helpers.tool("policy.load-corpus", {}, async () => {
      const [policies, currentConstitution] = await Promise.all([
        prisma.policyCorpus.findMany({
          where: { workspaceId: params.workspaceId },
          include: {
            proposal: { select: { id: true, title: true } },
            circle: { select: { id: true, name: true } },
          },
          orderBy: { acceptedAt: "asc" },
        }),
        prisma.constitution.findFirst({
          where: { workspaceId: params.workspaceId },
          orderBy: { version: "desc" },
        }),
      ]);

      return {
        policies,
        currentConstitution: currentConstitution ? {
          version: currentConstitution.version,
          bodyMd: currentConstitution.bodyMd,
          createdAt: currentConstitution.createdAt,
        } : null,
      };
    }),
    execute: async (context, helpers, runId, model) => {
      const policies = Array.isArray(context.policies) ? context.policies : [];
      const currentConstitution = context.currentConstitution as {
        version: number;
        bodyMd: string;
        createdAt: string | Date;
      } | null;

      if (policies.length === 0) {
        return {
          resultJson: {
            skipped: true,
            reason: "no_policies",
          },
        };
      }

      const synthesized = await helpers.tool("model.chat", { policyCount: policies.length }, async () => defaultModelGateway.chat({ model,
        workspaceId: params.workspaceId,
        agentRunId: runId,
        taskType: "AGENT",
        messages: [
          {
            role: "system",
            content: `You are a governance document synthesizer for a self-managing organization. Your task is to create or update a 10-point constitution document. First and foremost, the constitution MUST preserve its fixed Mission, Vision, and Purpose exactly as they are defined in the provided organizational context or the current constitution (if updating).

The 10 points should be generated ad hoc based on the most up-to-date and important parts of the organization's decisions and direction. Extract this context from the accepted policy corpus and any available internal sources.

The constitution should:
- Start with the fixed section for Mission, Vision, and Purpose.
- Follow with exactly 10 distinct ad-hoc constitutional points representing key organizational principles/rules.
- Organize references and supplementary policies beneath these points where relevant.
- Reference source proposals for traceability.
- Be written in clear, authoritative markdown.

${currentConstitution ? "You are UPDATING the existing constitution. You MUST preserve the existing Mission, Vision, and Purpose exactly as written. Update the 10 points based on the new policies." : "You are creating the FIRST constitution version. Establish the 10 points from the provided context."}`,
          },
          {
            role: "user",
            content: JSON.stringify({
              currentConstitution: currentConstitution?.bodyMd ?? null,
              policies: policies.map((p: Record<string, unknown>) => ({
                title: p.title,
                bodyMd: p.bodyMd,
                circle: p.circle,
                proposal: p.proposal,
                acceptedAt: p.acceptedAt,
              })),
            }),
          },
        ],
      }));

      const diffSummary = currentConstitution
        ? await helpers.tool("model.chat", { purpose: "diff-summary" }, async () => defaultModelGateway.chat({ model,
            workspaceId: params.workspaceId,
            agentRunId: runId,
            taskType: "SUMMARY",
            messages: [
              {
                role: "system",
                content: "Summarize the key differences between the old and new constitution versions in 2-3 bullet points. Be specific about what changed.",
              },
              {
                role: "user",
                content: JSON.stringify({
                  previous: currentConstitution.bodyMd.slice(0, 2000),
                  updated: synthesized.content.slice(0, 2000),
                }),
              },
            ],
          }))
        : null;

      // Persist the new constitution version
      const latestVersion = currentConstitution?.version ?? 0;
      const newVersion = await helpers.step("persist-version", { version: latestVersion + 1 }, async () =>
        createConstitutionVersion({
          workspaceId: params.workspaceId,
          bodyMd: synthesized.content,
          diffSummary: diffSummary?.content ?? (currentConstitution ? null : "Initial constitution generated from policy corpus."),
          triggerType: "agent",
          triggerRef: runId,
          modelUsed: synthesized.usage?.model ?? "unknown",
          promptTokens: synthesized.usage?.inputTokens ?? null,
          completionTokens: synthesized.usage?.outputTokens ?? null,
        })
      );

      return {
        resultJson: {
          constitutionId: newVersion.id,
          version: newVersion.version,
          diffSummary: diffSummary?.content ?? null,
          policyCount: policies.length,
        },
      };
    },
  });
}

export async function runAdviceRoutingAgent(params: {
  workspaceId: string;
  triggerRef: string;
  proposalId: string;
  triggerType?: AgentTriggerType;
}) {
  return executeAgentRun({
    agentKey: "advice-routing",
    workspaceId: params.workspaceId,
    triggerType: params.triggerType ?? "EVENT",
    triggerRef: params.triggerRef,
    goal: "Analyze proposal and recommend relevant advisors based on expertise and historical context.",
    payload: { proposalId: params.proposalId },
    plan: ["load-proposal", "search-knowledge", "query-expertise", "generate-recommendations"],
    buildContext: async (helpers) => {
      const proposal = await prisma.proposal.findUnique({
        where: { id: params.proposalId },
        select: { id: true, title: true, summary: true, bodyMd: true }
      });
      return { proposal };
    },
    execute: async (context, helpers, runId, model) => {
      if (!context.proposal) return { resultJson: { error: "Proposal not found" } };

      const suggestions = await helpers.tool("model.chat", { proposalId: params.proposalId }, async () => defaultModelGateway.chat({ model,
        workspaceId: params.workspaceId,
        agentRunId: runId,
        taskType: "AGENT",
        messages: [
          { role: "system", content: "Recommend advisors based on this proposal content. Output JSON with { advisors: [{ memberId, name, reason }] }." },
          { role: "user", content: JSON.stringify(context) },
        ],
      }));
      
      let parsed = { advisors: [] };
      try { parsed = JSON.parse(suggestions.content); } catch (e) {}

      await helpers.step("persist-suggestions", {}, async () => {
        await prisma.adviceProcess.updateMany({
          where: { proposalId: params.proposalId },
          data: { advisorySuggestionsJson: parsed },
        });
      });

      return { resultJson: parsed };
    },
  });
}

export async function runProcessLintingAgent(params: {
  workspaceId: string;
  triggerRef: string;
  processId: string;
  triggerType?: AgentTriggerType;
}) {
  return executeAgentRun({
    agentKey: "process-linting",
    workspaceId: params.workspaceId,
    triggerType: params.triggerType ?? "EVENT",
    triggerRef: params.triggerRef,
    goal: "Check if the proposal author gathered sufficient advice before execution.",
    payload: { processId: params.processId },
    plan: ["load-process-records", "evaluate-compliance", "persist-linting"],
    buildContext: async (helpers) => {
      const process = await prisma.adviceProcess.findUnique({
        where: { id: params.processId },
        include: { records: true }
      });
      return { process };
    },
    execute: async (context, helpers, runId, model) => {
      if (!context.process) return { resultJson: { error: "Process not found" } };

      const linting = await helpers.tool("model.chat", { processId: params.processId }, async () => defaultModelGateway.chat({ model,
        workspaceId: params.workspaceId,
        agentRunId: runId,
        taskType: "AGENT",
        messages: [
          { role: "system", content: "Evaluate advice process compliance. Were adequate experts consulted? Output JSON with { complianceScore: number, warnings: string[] }." },
          { role: "user", content: JSON.stringify(context) },
        ],
      }));

      let parsed = { complianceScore: 100, warnings: [] };
      try { parsed = JSON.parse(linting.content); } catch (e) {}

      await helpers.step("persist-linting", {}, async () => {
        await prisma.adviceProcess.update({
          where: { id: params.processId },
          data: { processLintJson: parsed },
        });
      });

      return { resultJson: parsed };
    },
  });
}


export async function runDailyCheckInAgent(params: {
  workspaceId: string;
  triggerRef: string;
  memberId: string;
  triggerType: "SCHEDULE" | "EVENT" | "MANUAL";
}) {
  return executeAgentRun({
    agentKey: "daily-check-in",
    workspaceId: params.workspaceId,
    triggerType: params.triggerType,
    triggerRef: params.triggerRef,
    goal: "Generate contextual check-in questions to monitor sentiment and prevent burnout.",
    payload: { memberId: params.memberId },
    plan: ["load-context", "generate-check-ins", "persist-check-ins"],
    buildContext: async (helpers) => {
      return { memberId: params.memberId };
    },
    execute: async (context, helpers, runId, model) => {
      const result = await helpers.step("persist-check-ins", {}, async () => {
        const { createCheckIn } = await import("@corgtex/domain");
        await createCheckIn(
          { role: "SYSTEM", id: "system" } as any,
          {
            workspaceId: params.workspaceId,
            memberId: params.memberId,
            questionText: "How are you feeling about your assigned tensions today?",
            questionSource: "AI",
          },
        );
        return { created: 1 };
      });
      return { resultJson: result };
    },
  });
}


export async function runSpendSubmissionAgent(params: {
  workspaceId: string;
  triggerRef: string;
  triggerType?: AgentTriggerType;
  amountCents: number;
  currency: string;
  category: string;
  description: string;
  vendor?: string | null;
  requesterEmail?: string | null;
}) {
  return executeAgentRun({
    agentKey: "spend-submission",
    workspaceId: params.workspaceId,
    triggerType: params.triggerType ?? "EVENT",
    triggerRef: params.triggerRef,
    goal: "Create and submit a spend request.",
    payload: {
      amountCents: params.amountCents,
      currency: params.currency,
      category: params.category,
      description: params.description,
      vendor: params.vendor ?? null,
      requesterEmail: params.requesterEmail ?? null,
    },
    plan: ["submit-spend"],
    buildContext: async () => ({}),
    execute: async (_context, helpers, _runId, _model) => {
      const result = await helpers.step("submit-spend", params, async () => {
        const { createSpend, submitSpend } = await import("@corgtex/domain");
        const actor = { kind: "agent" as const, agentSettings: { workspaceId: params.workspaceId } } as any;

        const spend = await createSpend(actor, {
          workspaceId: params.workspaceId,
          amountCents: params.amountCents,
          currency: params.currency,
          category: params.category,
          description: params.description,
          vendor: params.vendor,
          requesterEmail: params.requesterEmail,
        });

        const submitted = await submitSpend(actor, {
          workspaceId: params.workspaceId,
          spendId: spend.id,
        });

        return submitted;
      });

      return { resultJson: { spendId: result.spendId } };
    },
  });
}

export async function runAgentWorkflowJob(job: {
  id: string;
  workspaceId: string | null;
  type: string;
  payload: unknown;
}) {
  if (!job.workspaceId) {
    return null;
  }

  const payload = (job.payload ?? {}) as Record<string, unknown>;

  if (job.type === "agent.inbox-triage") {
    return runInboxTriageAgent({
      workspaceId: job.workspaceId,
      triggerRef: job.id,
      triggerType: "EVENT",
    });
  }

  if (job.type === "agent.daily-check-in") {
    const memberId = asString(payload.memberId);
    if (!memberId) return null;
    return runDailyCheckInAgent({
      workspaceId: job.workspaceId,
      triggerRef: job.id,
      memberId,
      triggerType: "SCHEDULE",
    });
  }

  if (job.type === "agent.meeting-summary") {
    return runMeetingSummaryAgent({
      workspaceId: job.workspaceId,
      triggerRef: job.id,
      meetingId: asString(payload.meetingId),
      triggerType: job.type === "agent.meeting-summary" && payload.triggerType === "MANUAL" ? "MANUAL" : "EVENT",
    });
  }

  if (job.type === "agent.action-extraction") {
    return runActionExtractionAgent({
      workspaceId: job.workspaceId,
      triggerRef: job.id,
      meetingId: asString(payload.meetingId),
      triggerType: payload.triggerType === "MANUAL" ? "MANUAL" : "EVENT",
    });
  }

  if (job.type === "agent.proposal-drafting") {
    return runProposalDraftingAgent({
      workspaceId: job.workspaceId,
      triggerRef: job.id,
      prompt: asString(payload.prompt),
      meetingId: asString(payload.meetingId) || null,
      triggerType: payload.triggerType === "API" ? "API" : "MANUAL",
    });
  }

  if (job.type === "agent.constitution-update-trigger") {
    return runConstitutionUpdateTriggerAgent({
      workspaceId: job.workspaceId,
      triggerRef: job.id,
      proposalId: asString(payload.proposalId),
      triggerType: payload.triggerType === "MANUAL" ? "MANUAL" : "EVENT",
    });
  }

  if (job.type === "agent.finance-reconciliation-prep") {
    return runFinanceReconciliationPrepAgent({
      workspaceId: job.workspaceId,
      triggerRef: job.id,
      spendId: asString(payload.spendId) || null,
      triggerType: payload.triggerType === "MANUAL" ? "MANUAL" : "EVENT",
    });
  }

  if (job.type === "agent.constitution-synthesis") {
    return runConstitutionSynthesisAgent({
      workspaceId: job.workspaceId,
      triggerRef: job.id,
      triggerType: payload.triggerType === "MANUAL" ? "MANUAL" : "EVENT",
    });
  }

  if (job.type === "agent.brain-maintenance") {
    return executeAgentRun({
      agentKey: "brain-maintenance",
      workspaceId: job.workspaceId,
      triggerType: payload.triggerType === "MANUAL" ? "MANUAL" : "SCHEDULE",
      triggerRef: job.id,
      goal: "Run weekly brain maintenance: freshness, dead links, orphans, Tier 3 cleanup, backlinks, discussions.",
      payload: {},
      plan: ["freshness-scan", "dead-link-scan", "orphan-detection", "tier3-cleanup", "backlink-rebuild", "discussion-maintenance"],
      buildContext: async (helpers) =>
        helpers.tool("brain.workspace-info", {}, async () => ({ workspaceId: job.workspaceId })),
      execute: async (_context, helpers, runId, _model) =>
        helpers.step("maintenance", {}, async () => {
          const result = await runBrainMaintenance({
            workspaceId: job.workspaceId!,
            agentRunId: runId,
          });
          return { resultJson: result };
        }),
    });
  }

  if (job.type === "agent.brain-absorb") {
    const sourceId = asString(payload.sourceId);
    if (!sourceId) return null;
    return executeAgentRun({
      agentKey: "brain-absorb",
      workspaceId: job.workspaceId,
      triggerType: "EVENT",
      triggerRef: job.id,
      goal: "Absorb a new source into the brain — update or create articles.",
      payload: { sourceId },
      plan: ["load-source", "classify", "match-articles", "absorb", "sync-knowledge", "rebuild-backlinks"],
      buildContext: async (helpers) =>
        helpers.tool("brain.load-source", { sourceId }, async () => ({ sourceId })),
      execute: async (_context, helpers, runId, model) =>
        helpers.step("absorb", { sourceId }, async () => {
          const result = await absorbSource({
            workspaceId: job.workspaceId!,
            sourceId,
            agentRunId: runId,
            model,
          });
          return { resultJson: result };
        }),
    });
  }

  if (job.type === "agent.advice-routing") {
    const proposalId = asString(payload.proposalId);
    if (!proposalId) return null;
    return runAdviceRoutingAgent({
      workspaceId: job.workspaceId!,
      triggerRef: job.id,
      proposalId,
      triggerType: "EVENT",
    });
  }

  if (job.type === "agent.process-linting") {
    const processId = asString(payload.processId);
    if (!processId) return null;
    return runProcessLintingAgent({
      workspaceId: job.workspaceId!,
      triggerRef: job.id,
      processId,
      triggerType: "EVENT",
    });
  }

  if (job.type === "agent.spend-submission") {
    const amountCents = Number(payload.amountCents ?? 0);
    if (!amountCents) return null;
    return runSpendSubmissionAgent({
      workspaceId: job.workspaceId!,
      triggerRef: job.id,
      triggerType: payload.triggerType === "MANUAL" ? "MANUAL" : "EVENT",
      amountCents,
      currency: asString(payload.currency) || "USD",
      category: asString(payload.category) || "general",
      description: asString(payload.description) || "Agent-generated spend request.",
      vendor: asString(payload.vendor) || null,
      requesterEmail: asString(payload.requesterEmail) || null,
    });
  }

  return null;
}
