import type { AgentRunStatus, AgentTriggerType } from "@prisma/client";
import { Prisma } from "@prisma/client";
import { createConstitutionVersion, type AgentKey } from "@corgtex/domain";
import { env, prisma, toInputJson } from "@corgtex/shared";
import { searchIndexedKnowledge } from "@corgtex/knowledge";
import { defaultModelGateway, resolveModel } from "@corgtex/models";
import { absorbSource } from "./brain-absorb";
import { runBrainMaintenance } from "./brain-maintenance";
import { isAgentEnabled, getAgentModelOverride, AGENT_REGISTRY, type RegisteredAgentKey } from "@corgtex/domain";

export type AgentOutcome = {
  resultJson: Prisma.InputJsonValue;
  approvalCheckpoint?: {
    summary: string;
    detail: Prisma.InputJsonValue;
  };
};

export type AgentHelpers = {
  step<T>(name: string, input: unknown, work: () => Promise<T>): Promise<T>;
  tool<T>(name: string, input: unknown, work: () => Promise<T>): Promise<T>;
};

export type AgentRunParams<TPayload extends Record<string, unknown>, TContext extends Record<string, unknown>> = {
  agentKey: AgentKey;
  workspaceId: string;
  triggerType: AgentTriggerType;
  triggerRef: string;
  goal: string;
  payload: TPayload;
  plan: string[];
  buildContext: (helpers: AgentHelpers, runId: string) => Promise<TContext>;
  execute: (context: TContext, helpers: AgentHelpers, runId: string, model: string) => Promise<AgentOutcome>;
};

export function toJson(value: unknown): Prisma.InputJsonValue {
  return toInputJson(value);
}

export function serializeError(error: unknown) {
  return error instanceof Error ? error.message : "Unknown agent runtime error.";
}

export function asString(value: unknown) {
  return typeof value === "string" ? value.trim() : "";
}

export function normalizeActionDrafts(value: unknown) {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((entry) => {
      if (!entry || typeof entry !== "object") {
        return null;
      }

      const record = entry as Record<string, unknown>;
      const title = asString(record.title);
      if (!title) {
        return null;
      }

      return {
        title,
        rationale: asString(record.rationale) || null,
      };
    })
    .filter((entry): entry is { title: string; rationale: string | null } => Boolean(entry));
}

export function normalizeProposalDraft(value: Record<string, unknown>, fallbackPrompt: string) {
  const title = asString(value.title) || fallbackPrompt.slice(0, 80) || "Draft proposal";
  const summary = asString(value.summary) || null;
  const bodyMd = asString(value.bodyMd) || asString(value.body) || `# ${title}\n\n${summary ?? "Proposal draft generated by agent."}`;

  return {
    title,
    summary,
    bodyMd,
  };
}

async function currentAgentRunCount(workspaceId: string) {
  return prisma.agentRun.count({
    where: {
      workspaceId,
      status: {
        in: ["PENDING", "RUNNING"],
      },
    },
  });
}

async function findExistingRun(agentKey: AgentKey, workspaceId: string, triggerType: AgentTriggerType, triggerRef: string) {
  return prisma.agentRun.findFirst({
    where: {
      workspaceId,
      agentKey,
      triggerType,
      triggerRef,
    },
    orderBy: {
      createdAt: "desc",
    },
  });
}

export async function executeAgentRun<TPayload extends Record<string, unknown>, TContext extends Record<string, unknown>>(
  params: AgentRunParams<TPayload, TContext>,
) {
  const existing = await findExistingRun(params.agentKey, params.workspaceId, params.triggerType, params.triggerRef);
  if (existing && existing.status !== "FAILED" && existing.status !== "CANCELLED") {
    return existing;
  }

  const isEnabled = await isAgentEnabled(params.workspaceId, params.agentKey);
  if (!isEnabled) {
    return { skipped: true, reason: "agent_disabled" };
  }

  if (env.AGENT_KILL_SWITCH) {
    return { skipped: true, reason: "kill_switch" };
  }

  const running = await currentAgentRunCount(params.workspaceId);
  if (running >= env.WORKSPACE_AGENT_MAX_CONCURRENCY) {
    return { skipped: true, reason: "concurrency_limit" };
  }

  const { checkBudget } = await import("@corgtex/domain");
  const budget = await checkBudget(params.workspaceId);
  if (!budget.allowed) {
    return { skipped: true, reason: "budget_exceeded" };
  }

  const run = await prisma.agentRun.create({
    data: {
      workspaceId: params.workspaceId,
      agentKey: params.agentKey,
      triggerType: params.triggerType,
      triggerRef: params.triggerRef,
      status: "RUNNING",
      goal: params.goal,
      planJson: toJson({
        steps: params.plan,
        payload: params.payload,
      }),
      startedAt: new Date(),
      contextJson: {},
    },
  });

  const accumulatedSteps: Prisma.AgentStepCreateManyInput[] = [];
  const accumulatedToolCalls: Prisma.AgentToolCallCreateManyInput[] = [];

  const helpers: AgentHelpers = {
    async step<T>(name: string, input: unknown, work: () => Promise<T>) {
      const startedAt = new Date();
      try {
        const output = await work();
        accumulatedSteps.push({
          agentRunId: run.id,
          name,
          status: "COMPLETED",
          inputJson: toJson(input) as any,
          outputJson: toJson(output) as any,
          startedAt,
          completedAt: new Date(),
          error: null,
        });
        return output;
      } catch (error) {
        accumulatedSteps.push({
          agentRunId: run.id,
          name,
          status: "FAILED",
          inputJson: toJson(input) as any,
          outputJson: Prisma.DbNull,
          startedAt,
          completedAt: new Date(),
          error: serializeError(error),
        });
        throw error;
      }
    },

    async tool<T>(name: string, input: unknown, work: () => Promise<T>) {
      const startedAt = new Date();
      try {
        const output = await work();
        accumulatedToolCalls.push({
          agentRunId: run.id,
          name,
          status: "COMPLETED",
          inputJson: toJson(input) as any,
          outputJson: toJson(output) as any,
          startedAt,
          completedAt: new Date(),
          error: null,
        });
        return output;
      } catch (error) {
        accumulatedToolCalls.push({
          agentRunId: run.id,
          name,
          status: "FAILED",
          inputJson: toJson(input) as any,
          outputJson: Prisma.DbNull,
          startedAt,
          completedAt: new Date(),
          error: serializeError(error),
        });
        throw error;
      }
    },
  };

  try {
    const override = await getAgentModelOverride(params.workspaceId, params.agentKey);
    const tier = AGENT_REGISTRY[params.agentKey as RegisteredAgentKey]?.defaultModelTier ?? "none";
    const model = resolveModel(tier, override);

    const context = await helpers.step("load-context", params.payload, () => params.buildContext(helpers, run.id));
    const outcome = await params.execute(context, helpers, run.id, model);
    const nextStatus: AgentRunStatus = outcome.approvalCheckpoint ? "WAITING_APPROVAL" : "COMPLETED";

    const finalRun = await prisma.$transaction(async (tx) => {
      if (accumulatedSteps.length > 0) {
        await tx.agentStep.createMany({ data: accumulatedSteps });
      }
      if (accumulatedToolCalls.length > 0) {
        await tx.agentToolCall.createMany({ data: accumulatedToolCalls });
      }

      const updated = await tx.agentRun.update({
        where: { id: run.id },
        data: {
          status: nextStatus,
          approvalRequired: Boolean(outcome.approvalCheckpoint),
          resultJson: toJson({
            ...((outcome.resultJson as Record<string, unknown>) ?? {}),
            approvalCheckpoint: outcome.approvalCheckpoint ?? null,
          }),
          contextJson: toJson(context),
          completedAt: nextStatus === "COMPLETED" ? new Date() : null,
          failedAt: null,
        },
      });

      await tx.event.create({
        data: {
          workspaceId: params.workspaceId,
          type: `agent.run.${nextStatus === "COMPLETED" ? "completed" : "waiting_approval"}`,
          aggregateType: "agentRun",
          aggregateId: updated.id,
          payload: toJson({
            agentKey: params.agentKey,
            goal: params.goal,
            status: nextStatus,
            resultJson: outcome.resultJson,
          }),
        },
      });

      return updated;
    });

    return finalRun;
  } catch (error) {
    const failedRun = await prisma.$transaction(async (tx) => {
      if (accumulatedSteps.length > 0) {
        await tx.agentStep.createMany({ data: accumulatedSteps });
      }
      if (accumulatedToolCalls.length > 0) {
        await tx.agentToolCall.createMany({ data: accumulatedToolCalls });
      }

      const updated = await tx.agentRun.update({
        where: { id: run.id },
        data: {
          status: "FAILED",
          approvalRequired: false,
          resultJson: toJson({
            error: serializeError(error),
          }),
          failedAt: new Date(),
        },
      });

      await tx.event.create({
        data: {
          workspaceId: params.workspaceId,
          type: "agent.run.failed",
          aggregateType: "agentRun",
          aggregateId: updated.id,
          payload: toJson({
            agentKey: params.agentKey,
            goal: params.goal,
            status: "FAILED",
            error: serializeError(error),
          }),
        },
      });

      return updated;
    });

    throw error;
  }
}















