import type { Metadata } from "next";
import { localeFromParams, type LocaleParams } from "../../../lib/locale";
import { buildMetadata } from "../../../lib/metadata";

const copy = {
  en: {
    metadata: {
      title: "Privacy Policy",
      description: "Corgtex privacy policy for workspace data, AI processing, MCP connectors, enterprise deployments, and open-core distribution.",
    },
    title: "Privacy Policy",
    updated: "Last updated: May 12, 2026",
    sections: [
      ["1. Overview", "Corgtex (\"we,\" \"our,\" or \"us\") provides a governed AI workforce platform for enterprise workspaces. This Privacy Policy explains how we collect, use, disclose, return, and protect personal information, workspace content, and connector data when you use Corgtex, including through Model Context Protocol (MCP) clients such as ChatGPT, Claude, Cursor, and other compatible tools."],
      ["2. Enterprise and open-core model", ["Corgtex is offered through an open-core model. Public or open-source code, documentation, examples, and demo materials do not include private customer workspace content.", "Enterprise capabilities, hosted deployments, support tooling, managed connectors, proprietary operations workflows, and customer-specific configuration are provided under commercial terms.", "If you use a customer-controlled or self-hosted deployment, your organization may independently control parts of hosting, logs, access, retention, and backup behavior. Your agreement with Corgtex or your organization controls where it conflicts with this policy."]],
      ["3. Information we collect", ["Account and identity data: name, email address, organization, workspace membership, role, authentication status, and consent records.", "Workspace data: documents, policies, governance structures, proposals, tensions, goals, actions, meetings, transcripts, summaries, Brain articles, comments, approvals, spend requests, ledger metadata, uploaded files, and other content you or your organization provide.", "Connector and MCP data: OAuth client metadata, workspace selection, scopes, access and refresh token records, tool names, tool inputs, tool outputs, authorization decisions, revocation events, and audit entries.", "Operational data: usage events, model usage, agent runs, workflow jobs, integration status, data-source sync status, support diagnostics, request metadata, security logs, device/browser metadata, and approximate location inferred from network data.", "Communications data: messages you send to Corgtex, support requests, demo or procurement forms, email replies, and meeting or sales notes."]],
      ["4. Data returned through MCP tools", ["When an authorized MCP client calls Corgtex tools, tool responses may return user-related and workspace-related fields needed for the request, including names, email addresses, roles, workspace IDs, organization names, item titles, status fields, timestamps, summaries, source snippets, member assignments, meeting information, governance records, finance metadata if enabled, and audit or runtime diagnostics.", "Some privileged tools can create, update, archive, restore, purge, retry, submit, reveal, or send workspace records according to the scopes shown during authorization and the user's Corgtex role. Sensitive tools, such as revealing a saved shared-tool credential, require explicit authorization and are audited.", "Corgtex tools are designed not to return raw passwords, secret tokens, unnecessary internal identifiers, full logs, or unrelated personal data by default. If a field is not needed for the user's request, we aim to remove or withhold it rather than disclose it broadly."]],
      ["5. How we use information", ["Provide, operate, secure, and support Corgtex.", "Authenticate users and MCP clients, enforce workspace membership, apply role-based permissions, and maintain audit trails.", "Process workspace governance, knowledge, meeting, action, finance, and support workflows requested by users or authorized agents.", "Generate workspace-specific search indexes, embeddings, summaries, recommendations, and AI-assisted outputs.", "Measure reliability, debug failures, prevent abuse, investigate security incidents, and comply with legal obligations.", "Improve Corgtex products and documentation. We do not use enterprise customer workspace content to train general-purpose public models unless an enterprise agreement or explicit customer configuration permits it."]],
      ["6. AI processing and model providers", ["Corgtex may send prompts, retrieved context, tool inputs, tool outputs, files, transcripts, summaries, and other workspace content to AI model providers or infrastructure providers to perform the actions you request.", "Model providers may include OpenAI, Anthropic, or other providers selected by Corgtex or by your organization. These providers process data under their own terms, enterprise controls, and retention settings where applicable.", "When you connect Corgtex to a third-party AI client through MCP, that client may receive Corgtex tool descriptions, the inputs you provide, and the tool results returned by Corgtex. Review the security practices and terms of the AI client before connecting."]],
      ["7. MCP authorization, scopes, and revocation", ["Corgtex MCP access uses browser authorization, OAuth-style tokens, PKCE where supported, workspace selection, and scope-based permissions.", "A connector is limited to the workspace selected during authorization and to the scopes granted to that client. Scopes may include read access, write access, support diagnostics, runtime repair, finance operations, member management, document upload, shared-tool management, or credential reveal permissions.", "You or your workspace administrator can revoke connector access, rotate credentials, deactivate members, or reduce scopes where the product or deployment configuration supports those controls."]],
      ["8. Sharing and subprocessors", ["We do not sell personal information.", "We may share information with service providers, subprocessors, model providers, hosting providers, analytics providers, communications providers, and support vendors that help us operate Corgtex under confidentiality and security obligations.", "We may disclose information when required by law, to protect rights or safety, to investigate abuse, in connection with a corporate transaction, or with your consent or your organization's instructions.", "Third-party MCP clients and AI providers that you connect are separate services. Their processing of data they receive is governed by their own privacy, security, and contractual terms."]],
      ["9. Security", ["We use technical and organizational safeguards designed to protect data, including encryption in transit, encryption at rest where supported, role-based access controls, workspace isolation, scoped connector tokens, secure session management, audit logs for sensitive operations, and least-privilege support workflows.", "No system is perfectly secure. You are responsible for keeping credentials private, authorizing only trusted connectors, reviewing requested scopes, and promptly revoking access that is no longer needed."]],
      ["10. Retention and deletion", ["We retain account, workspace, connector, audit, and operational data for as long as needed to provide Corgtex, meet contractual commitments, preserve security and audit history, comply with law, resolve disputes, and enforce agreements.", "Enterprise customers may have separate retention, export, deletion, backup, and audit requirements in their agreement or deployment configuration.", "After termination, we delete or anonymize customer workspace data within a commercially reasonable period unless retention is required by law, audit obligations, backup cycles, or the customer agreement."]],
      ["11. Your rights and choices", ["Depending on your location and relationship with Corgtex, you may have rights to access, correct, delete, export, object to, or restrict processing of personal information.", "Workspace content is often controlled by the enterprise customer or workspace administrator. We may direct requests about workspace data to that organization.", "You can reduce data shared with MCP clients by choosing narrower scopes, disconnecting third-party clients, disabling integrations, or asking your workspace administrator to remove access."]],
      ["12. International transfers", "Corgtex and its service providers may process information in the United States and other countries where we or they operate. Where required, we use appropriate transfer mechanisms and contractual protections."],
      ["13. Changes to this policy", "We may update this Privacy Policy from time to time. We will post the updated version on this page and update the last-updated date. Material changes may also be communicated through the product, email, or customer contacts."],
      ["14. Contact us", "For privacy inquiries, contact privacy@corgtex.com."],
    ],
  },
  es: {
    metadata: {
      title: "Política de privacidad",
      description: "Política de privacidad de Corgtex para datos de workspace, procesamiento de IA, conectores MCP, despliegues enterprise y distribución open-core.",
    },
    title: "Política de privacidad",
    updated: "Última actualización: 12 de mayo de 2026",
    sections: [
      ["1. Resumen", "Corgtex (\"nosotros\") ofrece una plataforma de fuerza laboral de IA gobernada para workspaces enterprise. Esta Política de privacidad explica cómo recopilamos, usamos, divulgamos, devolvemos y protegemos información personal, contenido de workspace y datos de conectores cuando usas Corgtex, incluso mediante clientes Model Context Protocol (MCP) como ChatGPT, Claude, Cursor y otras herramientas compatibles."],
      ["2. Modelo enterprise y open-core", ["Corgtex se ofrece con un modelo open-core. El código público o open-source, la documentación, los ejemplos y los materiales demo no incluyen contenido privado de workspaces de clientes.", "Las capacidades enterprise, los despliegues hospedados, las herramientas de soporte, los conectores gestionados, los flujos operativos propietarios y la configuración específica de clientes se ofrecen bajo términos comerciales.", "Si usas un despliegue controlado por el cliente o autoalojado, tu organización puede controlar de forma independiente parte del hosting, logs, acceso, retención y backups. Tu acuerdo con Corgtex o con tu organización prevalece si entra en conflicto con esta política."]],
      ["3. Información que recopilamos", ["Datos de cuenta e identidad: nombre, correo electrónico, organización, membresía de workspace, rol, estado de autenticación y registros de consentimiento.", "Datos de workspace: documentos, políticas, estructuras de gobernanza, propuestas, tensiones, objetivos, acciones, reuniones, transcripciones, resúmenes, artículos de Brain, comentarios, aprobaciones, solicitudes de gasto, metadatos contables, archivos subidos y otro contenido que tú o tu organización proporcionen.", "Datos de conectores y MCP: metadatos de cliente OAuth, selección de workspace, scopes, registros de tokens de acceso y refresh, nombres de herramientas, entradas de herramientas, salidas de herramientas, decisiones de autorización, eventos de revocación y entradas de auditoría.", "Datos operativos: eventos de uso, uso de modelos, ejecuciones de agentes, jobs de workflow, estado de integraciones, estado de sincronización de fuentes de datos, diagnósticos de soporte, metadatos de solicitudes, logs de seguridad, metadatos de dispositivo/navegador y ubicación aproximada inferida de datos de red.", "Datos de comunicaciones: mensajes que envías a Corgtex, solicitudes de soporte, formularios de demo o procurement, respuestas por correo electrónico y notas de reuniones o ventas."]],
      ["4. Datos devueltos mediante herramientas MCP", ["Cuando un cliente MCP autorizado llama herramientas de Corgtex, las respuestas pueden devolver campos relacionados con usuarios y workspaces que sean necesarios para la solicitud, incluidos nombres, correos electrónicos, roles, IDs de workspace, nombres de organización, títulos de elementos, estados, timestamps, resúmenes, fragmentos de fuentes, asignaciones de miembros, información de reuniones, registros de gobernanza, metadatos financieros si están habilitados y diagnósticos de auditoría o runtime.", "Algunas herramientas privilegiadas pueden crear, actualizar, archivar, restaurar, purgar, reintentar, enviar, revelar o mandar registros de workspace según los scopes mostrados durante la autorización y el rol del usuario en Corgtex. Las herramientas sensibles, como revelar una credencial guardada de una herramienta compartida, requieren autorización explícita y quedan auditadas.", "Las herramientas de Corgtex están diseñadas para no devolver contraseñas sin procesar, tokens secretos, identificadores internos innecesarios, logs completos ni datos personales no relacionados por defecto. Si un campo no es necesario para la solicitud del usuario, buscamos eliminarlo o retenerlo en lugar de divulgarlo ampliamente."]],
      ["5. Cómo usamos la información", ["Proporcionar, operar, proteger y dar soporte a Corgtex.", "Autenticar usuarios y clientes MCP, verificar membresía de workspace, aplicar permisos basados en roles y mantener auditorías.", "Procesar flujos de gobernanza, conocimiento, reuniones, acciones, finanzas y soporte solicitados por usuarios o agentes autorizados.", "Generar índices de búsqueda, embeddings, resúmenes, recomendaciones y salidas asistidas por IA específicas del workspace.", "Medir fiabilidad, depurar fallos, prevenir abuso, investigar incidentes de seguridad y cumplir obligaciones legales.", "Mejorar productos y documentación de Corgtex. No usamos contenido de workspaces enterprise para entrenar modelos públicos de propósito general salvo que un acuerdo enterprise o una configuración explícita del cliente lo permita."]],
      ["6. Procesamiento de IA y proveedores de modelos", ["Corgtex puede enviar prompts, contexto recuperado, entradas de herramientas, salidas de herramientas, archivos, transcripciones, resúmenes y otro contenido de workspace a proveedores de modelos de IA o infraestructura para ejecutar las acciones que solicitas.", "Los proveedores de modelos pueden incluir OpenAI, Anthropic u otros proveedores seleccionados por Corgtex o por tu organización. Estos proveedores procesan datos bajo sus propios términos, controles enterprise y configuraciones de retención cuando correspondan.", "Cuando conectas Corgtex a un cliente de IA de terceros mediante MCP, ese cliente puede recibir descripciones de herramientas de Corgtex, las entradas que proporciones y los resultados que Corgtex devuelva. Revisa las prácticas de seguridad y términos del cliente de IA antes de conectarlo."]],
      ["7. Autorización, scopes y revocación de MCP", ["El acceso MCP de Corgtex usa autorización en navegador, tokens de estilo OAuth, PKCE cuando está soportado, selección de workspace y permisos basados en scopes.", "Un conector se limita al workspace seleccionado durante la autorización y a los scopes concedidos a ese cliente. Los scopes pueden incluir acceso de lectura, acceso de escritura, diagnósticos de soporte, reparación de runtime, operaciones financieras, gestión de miembros, carga de documentos, gestión de herramientas compartidas o permisos para revelar credenciales.", "Tú o el administrador de tu workspace pueden revocar el acceso de conectores, rotar credenciales, desactivar miembros o reducir scopes cuando el producto o la configuración del despliegue admitan esos controles."]],
      ["8. Compartición y subprocesadores", ["No vendemos información personal.", "Podemos compartir información con proveedores de servicios, subprocesadores, proveedores de modelos, proveedores de hosting, proveedores de analítica, proveedores de comunicaciones y vendors de soporte que nos ayudan a operar Corgtex bajo obligaciones de confidencialidad y seguridad.", "Podemos divulgar información cuando lo exija la ley, para proteger derechos o seguridad, investigar abuso, en relación con una transacción corporativa, o con tu consentimiento o instrucciones de tu organización.", "Los clientes MCP y proveedores de IA de terceros que conectes son servicios separados. Su procesamiento de los datos que reciben se rige por sus propias políticas de privacidad, seguridad y términos contractuales."]],
      ["9. Seguridad", ["Usamos salvaguardas técnicas y organizativas diseñadas para proteger datos, incluido cifrado en tránsito, cifrado en reposo cuando está soportado, controles de acceso por rol, aislamiento de workspaces, tokens de conector con scopes, gestión segura de sesiones, logs de auditoría para operaciones sensibles y flujos de soporte de mínimo privilegio.", "Ningún sistema es perfectamente seguro. Eres responsable de mantener privadas tus credenciales, autorizar solo conectores de confianza, revisar los scopes solicitados y revocar con rapidez el acceso que ya no se necesite."]],
      ["10. Retención y eliminación", ["Retenemos datos de cuenta, workspace, conectores, auditoría y operación durante el tiempo necesario para proporcionar Corgtex, cumplir compromisos contractuales, preservar seguridad e historial de auditoría, cumplir la ley, resolver disputas y hacer cumplir acuerdos.", "Los clientes enterprise pueden tener requisitos separados de retención, exportación, eliminación, backups y auditoría en su acuerdo o configuración de despliegue.", "Después de la terminación, eliminamos o anonimizamos datos de workspace de clientes dentro de un periodo comercialmente razonable salvo que la ley, obligaciones de auditoría, ciclos de backup o el acuerdo con el cliente exijan retención."]],
      ["11. Tus derechos y opciones", ["Según tu ubicación y relación con Corgtex, puedes tener derechos a acceder, corregir, eliminar, exportar, oponerte o restringir el procesamiento de información personal.", "El contenido de workspace suele estar controlado por el cliente enterprise o administrador del workspace. Podemos dirigir solicitudes sobre datos de workspace a esa organización.", "Puedes reducir los datos compartidos con clientes MCP eligiendo scopes más limitados, desconectando clientes de terceros, desactivando integraciones o pidiendo al administrador de tu workspace que retire el acceso."]],
      ["12. Transferencias internacionales", "Corgtex y sus proveedores de servicios pueden procesar información en Estados Unidos y otros países donde operamos nosotros o ellos. Cuando sea requerido, usamos mecanismos de transferencia y protecciones contractuales adecuados."],
      ["13. Cambios a esta política", "Podemos actualizar esta Política de privacidad ocasionalmente. Publicaremos la versión actualizada en esta página y cambiaremos la fecha de última actualización. Los cambios materiales también pueden comunicarse dentro del producto, por correo electrónico o mediante contactos de cliente."],
      ["14. Contacto", "Para consultas de privacidad, contacta a privacy@corgtex.com."],
    ],
  },
} as const;

export async function generateMetadata({ params }: LocaleParams): Promise<Metadata> {
  const locale = await localeFromParams(params);
  return buildMetadata({ ...copy[locale].metadata, locale, path: "/privacy" });
}

export default async function PrivacyPage({ params }: LocaleParams) {
  const locale = await localeFromParams(params);
  const t = copy[locale];

  return (
    <div className="legal-page">
      <h1>{t.title}</h1>
      <p className="last-updated">{t.updated}</p>
      {t.sections.map(([title, body]) => (
        <section key={title}>
          <h2>{title}</h2>
          {Array.isArray(body) ? (
            <ul>{body.map((item) => <li key={item}>{item}</li>)}</ul>
          ) : typeof body === "string" && (title.includes("Contact") || title.includes("Contacto")) ? (
            <p>{body.replace("privacy@corgtex.com.", "")}<a href="mailto:privacy@corgtex.com" style={{ color: "var(--accent-red)" }}>privacy@corgtex.com</a>.</p>
          ) : (
            <p>{body}</p>
          )}
        </section>
      ))}
    </div>
  );
}
