import assert from "node:assert/strict";
import { test } from "node:test";
import { randomBytes } from "node:crypto";
import pg from "pg";
import { collectSchemaCatalog, compareSchemaCatalog } from "./lib/selfserve-schema-catalog.mjs";
import { AUDITOR_PRIVILEGES_SQL } from "./selfserve-validation-schema.mjs";

const source = new URL(process.env.QA_SCHEMA_TEST_DATABASE_URL || "http://missing");
assert.ok(["127.0.0.1", "localhost"].includes(source.hostname) && source.pathname === "/corgtex_test"
  && ["postgres:", "postgresql:"].includes(source.protocol), "Requires isolated local corgtex_test fixture");

test("PG16 catalog verification with unchanged ledger-only auditor", async t => {
  const suffix = randomBytes(6).toString("hex"), database = `catalog_${suffix}`, role = `auditor_${suffix}`;
  const password = randomBytes(24).toString("hex");
  const admin = new pg.Client({ connectionString: source.href });
  let fixture;
  const read = async user => {
    const url = new URL(source); url.pathname = `/${database}`;
    if (user) { url.username = role; url.password = password; }
    const client = new pg.Client({ connectionString: url.href });
    try {
      await client.connect();
      await client.query("BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY");
      if (user) {
        assert.equal((await client.query(AUDITOR_PRIVILEGES_SQL)).rows[0].can_write, false);
        assert.equal((await client.query("SELECT count(*)::int AS count FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind='r' AND c.relname<>'_prisma_migrations' AND has_table_privilege(current_user,c.oid,'SELECT')")).rows[0].count, 0);
      }
      return await collectSchemaCatalog(client);
    } finally { await client.query("ROLLBACK").catch(() => {}); await client.end(); }
  };
  try {
    await admin.connect();
    assert.equal(Math.floor(Number((await admin.query("SHOW server_version_num")).rows[0].server_version_num) / 10000), 16);
    await admin.query(`CREATE DATABASE ${database}`);
    await admin.query(`CREATE ROLE ${role} LOGIN PASSWORD '${password}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT CONNECTION LIMIT 2`);
    for (const setting of ["default_transaction_read_only=on", "statement_timeout=5000", "lock_timeout=1000", "search_path=public"]) await admin.query(`ALTER ROLE ${role} SET ${setting}`);
    const url = new URL(source); url.pathname = `/${database}`;
    fixture = new pg.Client({ connectionString: url.href }); await fixture.connect();
    await fixture.query(`CREATE TYPE public.mood AS ENUM ('ready','done');
      CREATE TABLE public._prisma_migrations (id text PRIMARY KEY);
      CREATE TABLE public.parent (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code text NOT NULL UNIQUE);
      CREATE TABLE public.child (id integer PRIMARY KEY, parent_id bigint REFERENCES public.parent(id) ON DELETE CASCADE,
        state public.mood NOT NULL DEFAULT 'ready', score integer NOT NULL DEFAULT 1 CHECK (score>0),
        doubled integer GENERATED ALWAYS AS (score*2) STORED);
      CREATE INDEX child_partial ON public.child (score DESC) INCLUDE (state) WHERE parent_id IS NOT NULL;
      CREATE INDEX child_expression ON public.child ((score+1));
      CREATE FUNCTION public.fixture_trigger() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;
      CREATE TRIGGER child_hook BEFORE INSERT ON public.child FOR EACH ROW EXECUTE FUNCTION public.fixture_trigger();
      GRANT CONNECT ON DATABASE ${database} TO ${role}; GRANT USAGE ON SCHEMA public TO ${role};
      GRANT SELECT ON public._prisma_migrations TO ${role};`);
    const expected = await read(false);
    await t.test("admin and narrow role are exactly equal, including nonempty sequences", async () => {
      assert.equal(expected.categories.sequences.length, 1);
      assert.equal(compareSchemaCatalog(expected, await read(true)).supportedSchemaMatch, true);
    });
    const cases = [
      ["columns", "ALTER TABLE child ALTER COLUMN score SET DEFAULT 7", "ALTER TABLE child ALTER COLUMN score SET DEFAULT 1"],
      ["columns", "ALTER TABLE child ALTER COLUMN state DROP NOT NULL", "ALTER TABLE child ALTER COLUMN state SET NOT NULL"],
      ["columns", "ALTER TABLE child ALTER COLUMN parent_id TYPE integer", "ALTER TABLE child ALTER COLUMN parent_id TYPE bigint"],
      ["columns", "ALTER TABLE child DROP COLUMN doubled; ALTER TABLE child ADD COLUMN doubled integer GENERATED ALWAYS AS (score*3) STORED", null],
      ["indexes", "DROP INDEX child_partial; CREATE INDEX child_partial ON child(score) WHERE parent_id IS NOT NULL", null],
      ["constraints", "ALTER TABLE child DROP CONSTRAINT child_parent_id_fkey; ALTER TABLE child ADD CONSTRAINT child_parent_id_fkey FOREIGN KEY(parent_id) REFERENCES parent(id) ON DELETE RESTRICT", null],
      ["constraints", "ALTER TABLE child DROP CONSTRAINT child_score_check; ALTER TABLE child ADD CONSTRAINT child_score_check CHECK(score>2)", null],
      ["columns", "ALTER TABLE parent ALTER COLUMN id SET GENERATED ALWAYS", "ALTER TABLE parent ALTER COLUMN id SET GENERATED BY DEFAULT"],
      ["sequences", "ALTER SEQUENCE parent_id_seq MAXVALUE 9223372036854775806", "ALTER SEQUENCE parent_id_seq MAXVALUE 9223372036854775807"],
      ["enums", "ALTER TYPE mood RENAME VALUE 'done' TO 'finished'", "ALTER TYPE mood RENAME VALUE 'finished' TO 'done'"],
      ["functions", "CREATE OR REPLACE FUNCTION fixture_trigger() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.id=0 THEN RETURN NULL; END IF; RETURN NEW; END $$", null],
      ["triggers", "ALTER TABLE child DISABLE TRIGGER child_hook", "ALTER TABLE child ENABLE TRIGGER child_hook"],
      ["relations", "CREATE TABLE extra_model(id integer)", "DROP TABLE extra_model"],
    ];
    for (const [category, sql, undo] of cases) await t.test(`detects ${category}: ${sql.split(" ").slice(0, 3).join(" ")}`, async () => {
      const before = await read(true);
      await fixture.query(sql);
      const result = compareSchemaCatalog(before, await read(true));
      assert.equal(result.supportedSchemaMatch, false);
      assert.ok(result.differences.some(d => d.category === category));
      assert.ok(!JSON.stringify(result).includes("fixture_trigger"));
      if (undo) await fixture.query(undo);
    });
    for (const [sql, undo] of [
      ["CREATE VIEW hidden_view AS SELECT id FROM child", "DROP VIEW hidden_view"],
      ["CREATE DOMAIN secret_domain AS integer CHECK(VALUE>0)", "DROP DOMAIN secret_domain"],
      ["ALTER TABLE child ENABLE ROW LEVEL SECURITY", "ALTER TABLE child DISABLE ROW LEVEL SECURITY"],
      ["CREATE TABLE partitioned(id integer) PARTITION BY RANGE(id)", "DROP TABLE partitioned"],
    ]) await t.test(`rejects unsupported ${sql.split(" ").slice(0, 3).join(" ")}`, async () => {
      await fixture.query(sql);
      await assert.rejects(read(true), /CATALOG_OBJECT_UNSUPPORTED/);
      await fixture.query(undo);
    });
    await fixture.query("CREATE SCHEMA outside_catalog");
    for (const [parentSchema, childSchema, rejected] of [
      ["public", "outside_catalog", true],
      ["outside_catalog", "public", true],
      ["outside_catalog", "outside_catalog", false],
    ]) await t.test(`inheritance ${parentSchema} parent / ${childSchema} child ${rejected ? "rejects" : "stays outside scope"}`, async () => {
      try {
        await fixture.query(`CREATE TABLE ${parentSchema}.inheritance_parent(id integer)`);
        const before = await read(true);
        await fixture.query(`CREATE TABLE ${childSchema}.inheritance_child() INHERITS (${parentSchema}.inheritance_parent)`);
        if (rejected) await assert.rejects(read(true), /CATALOG_OBJECT_UNSUPPORTED/);
        else assert.equal(compareSchemaCatalog(before, await read(true)).supportedSchemaMatch, true);
      } finally {
        await fixture.query(`DROP TABLE IF EXISTS ${childSchema}.inheritance_child`);
        await fixture.query(`DROP TABLE IF EXISTS ${parentSchema}.inheritance_parent`);
      }
    });
  } finally {
    if (fixture) await fixture.end();
    await admin.query(`DROP DATABASE IF EXISTS ${database}`);
    await admin.query(`DROP ROLE IF EXISTS ${role}`);
    await admin.end();
  }
});
