import { NextResponse } from "next/server";

// OpenAI ChatGPT Apps directory domain verification token.
// Generated by platform.openai.com/apps-manage during submission.
// See: https://platform.openai.com/docs/chatgpt-apps/domain-verification
const OPENAI_CHALLENGE_TOKEN = "iKB2aF3YTa35aMfwQNrrbilOpYt2R_KxtAxCGeJFjDg"; // gitleaks:allow

export async function GET() {
  return new NextResponse(OPENAI_CHALLENGE_TOKEN, {
    headers: {
      "Content-Type": "text/plain",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
